# playbook.yml
- name: Setup Docker and Registry on DigitalOcean VM
  hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt packages after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker registry image
      docker_image:
        name: registry
        tag: latest
        source: pull

    - name: Run Docker registry container
      docker_container:
        name: registry
        image: registry:latest
        state: started
        ports:
          - "5000:5000"
        restart_policy: always

    - name: Verify registry container is running
      shell: "docker ps | grep registry"
      register: registry_status
      failed_when: registry_status.stdout == ""
      changed_when: false
      ignore_errors: true

    - name: Display registry status
      debug:
        msg: "Registry container is running" if registry_status.stdout != "" else "Registry container failed to start"
